// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// learn
SEXP learn(std::string data, const bool RemoveDuplicates, const bool verbose, const size_t MaxEvents, const bool addBackground);
RcppExport SEXP ndl_learn(SEXP dataSEXP, SEXP RemoveDuplicatesSEXP, SEXP verboseSEXP, SEXP MaxEventsSEXP, SEXP addBackgroundSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type data(dataSEXP );
        Rcpp::traits::input_parameter< const bool >::type RemoveDuplicates(RemoveDuplicatesSEXP );
        Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP );
        Rcpp::traits::input_parameter< const size_t >::type MaxEvents(MaxEventsSEXP );
        Rcpp::traits::input_parameter< const bool >::type addBackground(addBackgroundSEXP );
        SEXP __result = learn(data, RemoveDuplicates, verbose, MaxEvents, addBackground);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// learnLegacy
SEXP learnLegacy(SEXP DFin, const bool RemoveDuplicates, const bool verbose);
RcppExport SEXP ndl_learnLegacy(SEXP DFinSEXP, SEXP RemoveDuplicatesSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type DFin(DFinSEXP );
        Rcpp::traits::input_parameter< const bool >::type RemoveDuplicates(RemoveDuplicatesSEXP );
        Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP );
        SEXP __result = learnLegacy(DFin, RemoveDuplicates, verbose);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
