// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// learn
SEXP learn(std::string data, const bool RemoveDuplicates, const bool verbose, const size_t MaxEvents, const bool addBackground);
RcppExport SEXP _ndl_learn(SEXP dataSEXP, SEXP RemoveDuplicatesSEXP, SEXP verboseSEXP, SEXP MaxEventsSEXP, SEXP addBackgroundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const bool >::type RemoveDuplicates(RemoveDuplicatesSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const size_t >::type MaxEvents(MaxEventsSEXP);
    Rcpp::traits::input_parameter< const bool >::type addBackground(addBackgroundSEXP);
    rcpp_result_gen = Rcpp::wrap(learn(data, RemoveDuplicates, verbose, MaxEvents, addBackground));
    return rcpp_result_gen;
END_RCPP
}
// learnLegacy
SEXP learnLegacy(SEXP DFin, const bool RemoveDuplicates, const bool verbose);
RcppExport SEXP _ndl_learnLegacy(SEXP DFinSEXP, SEXP RemoveDuplicatesSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type DFin(DFinSEXP);
    Rcpp::traits::input_parameter< const bool >::type RemoveDuplicates(RemoveDuplicatesSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(learnLegacy(DFin, RemoveDuplicates, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ndl_learn", (DL_FUNC) &_ndl_learn, 5},
    {"_ndl_learnLegacy", (DL_FUNC) &_ndl_learnLegacy, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ndl(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
